## Problem set 4.4 (p 242)

In [2]:
import numpy as np

In [3]:
def getProjMat(a):
    if (type(a) is not np.ndarray):
        a = np.array(a)
    aat = np.outer(a,a)
    ata = np.dot(a,a)
    bigp = aat/ata
    return bigp

In [4]:
def getProjection(b,a): #b onto a
    if (type(a) is not np.ndarray):
        a = np.array(a)
    if (type(b) is not np.ndarray):
        b = np.array(b)
    ata = np.dot(a,a)
    atb = np.dot(a,b)
    x = atb/ata
    littlep = x*a
    return littlep

In [5]:
def normVecs(*vecs):
    orthvecs = []
    for ii in range(0,len(vecs)):
        if type(vecs[ii] is not np.ndarray):
            vec = np.array(vecs[ii])
        orthvecs.append(vec / np.sqrt(np.dot(vec,vec)))
        assert np.dot(orthvecs[ii],orthvecs[ii])==1, 'vectors are not unit length'
    return orthvecs 

In [6]:
def joinVecs(*qvecs):
    Qmat = np.column_stack(qvecs)
    if np.shape(Qmat)[0] != np.prod(np.shape(qvecs[0])):
        raise Exception('concatenation failed')
    else:
        return Qmat

In [8]:
#note! python range does not include end... 

def gs(*inputs): #tested only for two vectors so far
    vecs = []
    for vv in range(0,len(inputs)):
        vecs.append(np.array(inputs[vv]))
    qvecs = []
    qvecs.append(vecs[0])
    for ii in range(1,len(vecs)): #starting from second vector i.e. index 1
        qitr = vecs[ii]
        
        for jj in range(0,ii):            
            qitr = qitr - (getProjection(vecs[ii],qvecs[jj])) #q = b - p = b - xa
            
            assert np.isclose(np.dot(qitr,qvecs[jj]),0), 'vectors are not orthogonal'
        qvecs.append(qitr)
        
    for qq in range(0,len(qvecs)): #schmidt!
        qvecs[qq] = qvecs[qq] / np.sqrt(np.dot(qvecs[qq],qvecs[qq]))
    return qvecs

### Problem 11

In [5]:
a = np.array([1,3,4,5,7])
b = np.array([-6,6,8,0,8])
q1 = a
p = getProjection(b,q1)

In [6]:
e = b-p
print(e)

q2 = e

assert np.dot(q1,q2) == 0, 'vectors are not orthogonal'

[-7.  3.  4. -5.  1.]


In [9]:
#normalize to unit length
orthonormalvecs = normVecs(q1,q2)
orthonormalvecs[0]*10 #correct! [1,3,4,5,7]*(1/10)

array([1., 3., 4., 5., 7.])

### Problem 15 

In [10]:
A = np.array([[1,1],[2,-1],[-2,4]])
print(A)

[[ 1  1]
 [ 2 -1]
 [-2  4]]


In [17]:
q1 = A[:,0]
p = getProjection(A[:,1],q1)
q2 = A[:,1]-p
print(q1)
print(q2)

orthvecs = normVecs(q1,q2)
print(orthvecs)
np.dot(orthvecs[1],orthvecs[1])

[ 1  2 -2]
[2. 1. 2.]
[array([ 0.33333333,  0.66666667, -0.66666667]), array([0.66666667, 0.33333333, 0.66666667])]


1.0

In [35]:
c = np.ones(np.shape(q2))

cprojq1 = getProjection(c,q1)
cprojq2 = getProjection(c,q2)

q3 = c - cprojq1 - cprojq2

q3 = q3 / np.sqrt(np.dot(q3,q3))

print(q3)

#q3 should be in null space of A^T (orthogonal to column space)

Q = joinVecs(q1,q2)
print(Q)

[-0.66666667  0.66666667  0.33333333]
[[ 1.  2.]
 [ 2.  1.]
 [-2.  2.]]


In [66]:
print(orthvecs[0]*3) #1,2,-2
print(orthvecs[1]*3) #2,1,2

print(q3*3) #correct (two valid answers)
#basically the same vector, just negative version, as answer (deg = 180)
#from math import acos, degrees
#degrees(acos(np.dot(q3, np.array([2,-2,-1])/3))) 

[ 1.  2. -2.]
[2. 1. 2.]
[-2.  2.  1.]


In [70]:
#this should work but doesn't..?
R = Q.T@A
print(R)
QR = Q@R
print(QR)

[[ 9. -9.]
 [ 0.  9.]]
[[  9.   9.]
 [ 18.  -9.]
 [-18.  36.]]


In [73]:
y = np.array([1,2,7])
x = ((np.linalg.inv(A.T@A))@A.T)@y #solving least squares
print(x) #1,2

[1. 2.]


### Problem 16

In [94]:
#to get multiple "x" of a which is closest to b, do, atb/ata
a = np.array([4,5,2,2])
b = np.array([1,2,0,0])
x = (np.dot(a,b))/(np.dot(a,a))
print(x) #2/7, correct
       
q1 = a
p = x*a
q2 = b - p

assert np.isclose(np.dot(q1,q2),0), 'vectors are not orthogonal'

q1 = q1 / np.sqrt(np.dot(q1,q1))
q2 = q2 / np.sqrt(np.dot(q2,q2))

assert (np.dot(q1,q1) == 1) & (np.dot(q2,q2) == 1), 'vectors are not unit length'

print(q1*7) #4,5,2,2
print(q2*7) #-1,4,-4,-4

0.2857142857142857
[4. 5. 2. 2.]
[-1.  4. -4. -4.]


### Problem 17

In [111]:
a = [1,1,1]
b = [1,3,5]

p = getProjection(b,a) #p = xa where x = atb/ata
print(p) #3,3,3

e = b-p
print(e) #-2,0,2

print('')

q1 = a/np.sqrt(np.dot(a,a))
print(q1)
assert(np.allclose(q1, np.ones([1,3])/np.sqrt(3))) #pretty close


q2 = e/np.sqrt(np.dot(e,e))
print(q2)
assert np.allclose(q2, np.array([-1,0,1])/np.sqrt(2)) #pretty close

[3. 3. 3.]
[-2.  0.  2.]

[0.57735027 0.57735027 0.57735027]
[-0.70710678  0.          0.70710678]


### Problem 18

In [183]:
a = np.array([1, -1, 0,0])
b = np.array([0,1,-1,0])
c = [0,0,1,-1]

In [149]:
#debugging - seems to check out
if False: 
    vecs = [a,b]
    print(vecs)
    q = []
    q.append(vecs[0])
    print(q)

    qitr = vecs[1]
    p = getProjection(vecs[1],q[0])
    print(p)
    qitr = qitr - p
    print(qitr)
    np.dot(qitr,q[0])

    q.append(qitr)
    print(q)

In [220]:
q = gs(a,b,c) #wow surprisingly works out of the box..
print(q[0]) #1,-1,0,0
print(q[1]) #0.5, 0.5, -1, 0
print(q[2]) #1/3,1/3,1/3,-1

d = np.array([1,1,1,1]) #all orthogonal to this guy

[ 1 -1  0  0]
[ 0.5  0.5 -1.   0. ]
[ 0.33333333  0.33333333  0.33333333 -1.        ]


<img src="https://i.imgur.com/yOiiYRU.png">

### Problem 19

In [249]:
A = np.array([[-1,1],[2,1],[2,4]])
np.shape(A)
q = gs(A[:,0],A[:,1])
Q = joinVecs(q[0],q[1])
print(A)

print(Q*3) #correct

R = Q.T@A

print(R) #correct

#squared diagonals of R, are the pivots of ATA;
#because RTR is the product of upper and lower triangular matrices, i.e. the diagonal gets multiplied twice 

[[-1  1]
 [ 2  1]
 [ 2  4]]
[[-1.  2.]
 [ 2. -1.]
 [ 2.  2.]]
[[3. 3.]
 [0. 3.]]


### Problem 21

In [289]:
a1 = [1,1,1,1]
a2 = [-2,0,1,3]
A = joinVecs(a1,a2)

q = gs(a1,a2)
Q = joinVecs(q[0],q[1])

print(Q) #correct

b = [-4,-3,3,0]

projb = (Q@Q.T)@b 

print(projb) #correct, [-3.5,-1.5,-0.5,1.5]

[[ 0.5        -0.69337525]
 [ 0.5        -0.13867505]
 [ 0.5         0.13867505]
 [ 0.5         0.69337525]]
[-3.5 -1.5 -0.5  1.5]


### Problem 22

In [14]:
#find *orthogonal* vectors only
a = np.array([1,1,2])
b = np.array([1,-1,0])
c = np.array([1,0,4])

q1 = a
q2 = b - getProjection(b,q1)
q3 = c - getProjection(c,q2) - getProjection(c,q1)

print(q1,q2,q3) #correct!

[1 1 2] [ 1. -1.  0.] [-1. -1.  1.]


### Problem 31

In [51]:
Q = joinVecs([1, -1,-1,-1],[-1,1,-1,-1],[-1,-1,1,-1],[-1,-1,-1,1])/2
print(Q)

b = [1,1,1,1]

bq1 = getProjection(b,Q[:,0])
print(bq1) #180 on other side of q1 - correct (-0.5, -0.5, -0.5, 0.5)

A = Q[:,0:2]

bq2 = (A@(np.linalg.inv(A.T@A))@A.T)@b
print(bq2) #correct (0,0,1,1)

#alternatively, from answers, add:
bq2 = bq1 + getProjection(b,Q[:,1])
print(bq2)

[[ 0.5 -0.5 -0.5 -0.5]
 [-0.5  0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5 -0.5]
 [-0.5 -0.5 -0.5  0.5]]
[-0.5  0.5  0.5  0.5]
[0. 0. 1. 1.]
[0. 0. 1. 1.]


### Problem 32

In [63]:
u1 = np.array([0,1])
uut1 = np.outer(u1,u1)
print(uut1)

Q1 = np.eye(np.shape(u1)[0]) - 2*(uut1)
print(Q1) #reflection matrix - flips across x-axis (i.e. y-values flip sign)

u2 = np.array([0, np.sqrt(2)/2,np.sqrt(2)/2])
uut2 = np.outer(u2,u2)
print(uut2)

Q2 = np.eye(np.shape(u2)[0]) - 2*(uut2)
print(np.round(Q2,2)) #reflection matrix - rotates whole space around x-axis 

Q1@np.array([1,2]) #flip y-coordinate

Q2@np.array([1,1,1]) #flip y and z coordinates 

[[0 0]
 [0 1]]
[[ 1.  0.]
 [ 0. -1.]]
[[0.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]]
[[ 1.  0.  0.]
 [ 0. -0. -1.]
 [ 0. -1. -0.]]


array([ 1., -1., -1.])